@startuml

object Instance {
 インスタンス化(実行中)
}

object ScriptableObject {
 ScriptableObject(実行中)
}

object JsonPlayerData {
 JsonPlayerData(ゲームを終了、開始時)
}

object CSVMasterData {
 CSVMasterData(マスターデータ)
}

Instance --> ScriptableObject : ゲーム実行中に保存
ScriptableObject --> Instance : ゲーム実行中にロード

ScriptableObject --> JsonPlayerData : ゲームが終了したときに保存
JsonPlayerData --> ScriptableObject : ゲームが開始したときにロード

JsonPlayerData --> CSVMasterData : ゲームが終了したときに保存
CSVMasterData --> JsonPlayerData : Jsonに保存されているバージョンとCSV(サーバ)に保存されているバージョンが違ったときにロード

@enduml