@startuml

class SoulCard {
    -cardID : int
    -image : Sprite
    -soulName : string
    -soulLevel : int
    -soulAbility : SoulAbility
    -explanatoryText : string
    -status : Status
    -traitList : List<TraitWrapper>

    +CardID : int
    +Image : Sprite
    +SoulName : string
    +SoulLevel : int
    +SoulAbility : SoulAbility
    +ExplanatoryText : string
    +Status : Status
    +TraitList : List<TraitWrapper>
}

class SoulAbility {
    -abilityName : string
    -coolTime : float
    -effect : string
    -effectText : string
    +AbilityName : string
    +CoolTime : float
    +Effect : string
    +EffectText : string
}

class SoulCardList {
    -soulCardList : List<SoulCard>
}

class Status {
    -hp : int
    -attack : int
    -defence : int
    -coolTime : float
    -range : float
    -bulletSpeed : float
    -effectTime : float
    -bulletNum : int
    -penetration : int
    -moveSpeed : float
    -growthSpeed : float
    -luck : int
    +Hp : int
    +Attack : int
    +Defence : int
    +CoolTime : float
    +Range : float
    +BulletSpeed : float
    +EffectTime : float
    +BulletNum : int
    +Penetration : int
    +MoveSpeed : float
    +GrowthSpeed : float
    +Luck : int
}

class TraitWrapper {
    -_trait : ITraitInterface
}

interface ITraitInterface {
}

class AdjacencyList {
    -_adjacencyList : Dictionary<SoulCard, List<SoulCard>>
    -soulCardList : List<SoulCard>
    +AddCombination(SoulCard, SoulCard) : void
    +CanCombine(SoulCard, SoulCard) : bool
}

class SoulCombination {
    -ingredient1 : SoulCard
    -ingredient2 : SoulCard
    -result : SoulCard
    +IsValidCombination(SoulCard, SoulCard) : bool
}

class SoulMixManager {
    -soulCombinations : List<SoulCombination>
    +CombineSouls(SoulCard, SoulCard) : SoulCard
}

SoulCard --> "1" SoulAbility : has
SoulCard --> "1" Status : has
SoulCard --> "*" TraitWrapper : has

SoulCard "1" -- "*" SoulCardList : contains
SoulCard "2" -- "1" SoulCombination : ingredients > result
SoulMixManager --> "*" SoulCombination : manages

AdjacencyList --> "n" SoulCard : manages

@enduml
